version: '2'

services:
   db:
     image: mysql:5.7
     volumes:
       - ${COMPOSE_PROJECT_NAME}_db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     ports:
       - 80
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ${COMPOSE_PROJECT_NAME}_wp_data:/var/www/html/wp-content

volumes:
  ${COMPOSE_PROJECT_NAME}_db_data:
  ${COMPOSE_PROJECT_NAME}_wp_data: