version: '3.7'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     image: wordpress:latest
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - wp_data:/var/www/html/wp-content
     deploy:
       mode: replicated
       replicas: 1
       labels:
         - traefik.http.routers.${APP_HOSTNAME}.rule=Host(`${APP_HOSTNAME}.${APP_DOMAIN}`)
         - traefik.http.routers.${APP_HOSTNAME}.tls=true
         - traefik.http.services.${APP_HOSTNAME}.loadbalancer.server.port=80
         - traefik.http.routers.${APP_HOSTNAME}.tls.certresolver=le
         - traefik.enable=true
         - traefik.docker.network=traefik-net
  
     networks:
       - traefik-net

volumes:
  db_data:
  wp_data:
  
networks:
  traefik-net:
    external: true